### ISSUE TITLE
Notify user when auth token is expired

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#162]
as a user I want to get some message when my token is expired and get logout automatically, so I will know that I need to sign-in again.

## Acceptance criteria

* [x] when the token expired, the user could see that he is not authorized 

## Tasks
* [ ] 

## Analysis

When the user tries to get a page with his private dataset, but not logined - he gets `Sorry, the page was not found` 404 page.
The first several times when I met this, I had no idea that my token was expired.

It has been decided https://github.com/datahq/frontend/issues/135 not to return 403 forbidden page for security reasons.

But we could redirect user to login page instead, or show some message, when user have a token, but it is expired.

**Comment by zelima** [comment]
FIXED we notify user that might need to login
