### ISSUE TITLE
Search box in publisher page is not working

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#163]
There is a situation when you cannot find dataset on users dashboard's search box, but it can be found on the main search page. For example, dataset http://datahub.io/JohnSnowLabs/ietf-language-tags-list
  
## Acceptance criteria

* [x] search is working properly on publisher page

## Tasks

* [x] analysis
* [x] implementation

## Analysis

It seems that the problem is not in filtering but dataset not appearing on users page at all:

* if you try and search for that word with regular search (ctrl+f) you will not find it there
* how many results are we displaying per page?
counted roughly and seems 100 (while total number of datasets is 160)
* how to access other 60?

### Latest updates

* since we implemented pagination, our filtering system looks for only current page*which is 20 datasets), but we want to search for all datasets, that's why we need to replace filtering to actual search via metastore.

**Comment by zelima** [comment]
@Mikanebu Could you please provide a bit more info for this case Eg: 
* how to reproduce
* is this the only dataset? 
* It is not there at all or filter is not working?
* maybe screenshots?

That link to dataset gives almost nothing helpful to me.

And also please add to relevant milestone

**Comment by Mikanebu** [comment]
@zelima When you search from users dashboard https://datahub.io/JohnSnowLabs for keyword `IETF`, there will be no results showing, but if you search from https://datahub.io/search?q=IETF it will show this dataset https://datahub.io/JohnSnowLabs/ietf-language-tags-list

**Comment by anuveyatsu** [comment]
@Mikanebu dashboard is at `/dashboard`, you're talking about publisher page

**Comment by Mikanebu** [comment]
@anuveyatsu Yes, it is publisher page

**Comment by anuveyatsu** [comment]
@Mikanebu Probably, the search should work differently here - filtering is not the best solution. On the other hand, we need pagination here but it is already under consideration.

**Comment by zelima** [comment]
@Mikanebu @anuveyatsu OK, I did a bit more research here and it seems that the problem is not in filtering but dataset not appearing on users page at all:
* if you try and search for that word with regular search  (`ctrl+f`) you will not find it there
* how many results are we displaying per page? 
  * counted roughly and seems 100 (while total number of datasets is 160) 

PS. @Mikanebu could you please update issue description properly, according to Datopian standards (tasks, acceptance criteria, analysis etc...) and move all this in the analysis section.

**Comment by Mikanebu** [comment]
@anuveyatsu I think, we need to filter using the list of all datasets, not just current page (20 datasets)

**Comment by anuveyatsu** [comment]
@Mikanebu then it is a proper search box. Probably you're right otherwise people can filter using a browser's "search on page" feature. @zelima what do you think?

**Comment by zelima** [comment]
@anuveyatsu Agree with @Mikanebu

**Comment by Mikanebu** [comment]
FIXED, now we search through entire publisher's datasets via metastore.
