### ISSUE TITLE
Zip served with incorrect MIME type

### ISSUE THREAD

**Issue by wetneb** [datahq/frontend#167]
On https://datahub.io/core/cofog, when I click on the Data Package Zip link, I go to https://pkgstore.datahub.io/core/cofog/datapackage_zip/data/ed438b8b276d0169131523969f4e3582/datapackage_zip.zip , which displays as a text file in my browser (Firefox). This is because the content-type header is wrong:

> HTTP/2 200
> date: Wed, 10 Jan 2018 09:34:16 GMT
> content-type: text/plain
> content-length: 56843
> set-cookie: __cfduid=d446758f7197d4cddb0b88de4275d45d01515576856; expires=Thu, 10-Jan-19 09:34:16 GMT; path=/; domain=.datahub.io; HttpOnly
> x-amz-id-2: RHeDmzidz6ufk1dSz5kVAi8ATyz9iOcn00zVbXBsYA4d0l8XvNz+hDcMLWQdh7LJxucXLu0xSdo=
> x-amz-request-id: 35E0244A4650BDC8
> last-modified: Wed, 15 Nov 2017 08:51:16 GMT
> etag: "ed438b8b276d0169131523969f4e3582"
> accept-ranges: bytes
> server: cloudflare
> cf-ray: 3daea3b77ff834ca-LHR

it should be `application/zip`, not `text/plain`.

**Comment by Mikanebu** [comment]
@wetneb Thanks for reporting this. We will investigate

**Comment by rufuspollock** [comment]
@Mikanebu what's the update?

**Comment by zelima** [comment]
Will be fixed in this milestone. Moving this issue where it belongs https://github.com/datahq/planner/issues/20
Feel free to re-open if necessary

**Comment by zelima** [comment]
@wetneb thanks again for reporting this! Updating:
* Thanks to you, we're now allowing to guess content type to the tool that is used to export stuff on S3. This would definitely come up at some point in future.
* Anyway we are setting the content type to `plain/text` and this is done on purpose as we do not want to have issues with security. Eg We don't want to have HTML or Javascript files that may be used in a harmful way.

**Comment by wetneb** [comment]
hmm - that looks quite curious to me. Don't you know for sure that these data packages are zip files? At least this is displayed by your UI. I don't get why you need to guess the content type of the data you hold - isn't it something you control at upload time and keep track of?

As a user this is very impractical, and can lead to big performance issues if the browser tries to display a big zip as plain text… At least you should warn the user that they should not click on the link but instead do a right click and "Save as".

Who else serves zip files purposely as `plain/text` in this way?

**Comment by akariv** [comment]
I guess we should have two separate policies here - original files should be served as `text/plain` (or even better I think `application/octet-stream`) and derived files should be served using the correct mime-types.
@rufuspollock @zelima wdyt?

**Comment by wetneb** [comment]
That sounds a lot better to me!

**Comment by rufuspollock** [comment]
@akariv agreed.

**Comment by zelima** [comment]
FIXED  back in March.
