### ISSUE TITLE
We have `unlisted` datasets which are listed in search page

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#179]
We want to fix our search page, so it will not show `unlisted` datasets

## Acceptance criteria

* [ ] there is no more `unlisted` datasets in search page

## Tasks 

* [ ] debug this issue

## Analysis

Please, try to search https://datahub.io/search?q=employment and you will see some `unlisted` datasets under `core` user

**Comment by zelima** [comment]
@Mikanebu Think this belongs to metstore https://github.com/datahq/metastore can you please move?

**Comment by Mikanebu** [comment]
Issue moved to [datahq/metastore #26](https://github.com/datahq/metastore/issues/26) via [**ZenHub**](https://www.zenhub.com/)
