### ISSUE TITLE
Not display "This is a preview version ..." under non-tabular resources

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#181]
"This is a preview version. There might be more data in the original version." is displayed for zip or non-tabular resource while they can't have tables. 

Reproduce:  try publishing non-tabular file  Eg README.md

## Acceptance Criteria

* [ ] no misrelated messages under resources

## Tasks 

* [ ] remove them

**Comment by anuveyatsu** [comment]
This is related to #111 and I think we should have placeholders rather than hiding those messages/links.

**Comment by zelima** [comment]
Sounds better. Closing as Duplicate of #111
