### ISSUE TITLE
[Search page] Core datasets appear not on the top of the search result

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#193]
Reported here: datahq/datahub-qa#70

We want to show `core` datasets first prior others

## Acceptance criteria

* [x] The `core` user should appear first

### How to reproduce: 

* Go to '\search` page and search for `gdp`

### Output

`core` datasets appear did not appear first in the result list

**Comment by zelima** [comment]
FIXED/DUPLICATE of https://github.com/datahq/metastore/issues/27

**Comment by Mikanebu** [comment]
If I search for `Mauna Loa`, the core dataset is not on the top.

**Comment by AcckiyGerman** [comment]
If I search for Mauna Loa, the core dataset is not on the top :cry:
