### ISSUE TITLE
Search page does not show all results

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#195]
Reported here: datahq/datahub-qa#67

We want to fix search page, so I will show all results

## Acceptance criteria

* [ ] It should show all results in one page or with pagination

## Tasks

* [x] Add pagination

### How to reproduce: 

* Go to '\search` page and seach for `core`

### Output

It shows only first 20 datasets out of 78, no pagination implemented yet

**Comment by zelima** [comment]
FIXED we have pages now datahub.io/search
