### ISSUE TITLE
[frontend] Issue with encoding of the title

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#215]
Issue reported here https://github.com/datahq/datahub-qa/issues/37
See https://datahub.io/joelgombin/ville_vitry_subventions_2017: the title of the page - which was passed by the CLI tool - has encoding issue, whereas the previewing of the CSV resource is fine.

## Acceptance criteria

* [x] all information on showcase page is displayed correctly

## Tasks

* [x] debug
* [x] analysis on how to fix
* [x] implementation

## Analysis

The reason behind this problem is that browser by default using `utf-8` encoding to decode data which comes originally from  specstore.  Tried to configure amazon s3 bucket, but unfortunately, it did not help by assigning metadata `encoding: utf-8`, but decoding with `iso-8859-9` which translates `Réunion` to `RÃ©union`.
https://datahub.io/Mikanebu/test5

```
              "pathType": "local",
              "name": "test5",
              "format": "csv",
              "mediatype": "text/csv",
              "encoding": "ISO-8859-9",
```
As a result, we cannot encode using `utf-8` when it decoded using different encoding.
We decided that encoding work should be handled on frontend side if we pass encoding from the backend. For example, if you take a look on GitHub files. 
Preview of data looks fine: https://github.com/frictionlessdata/test-data/blob/master/files/csv/encodings/iso8859.csv
However, the original data is different: https://raw.githubusercontent.com/frictionlessdata/test-data/master/files/csv/encodings/iso8859.csv

Tested by passing encoding `latin1` to the frontend manually and it worked. 

The solution would be the following: 
* when loading Dataset object add encoding key into descriptor (just like for File class)
* then in the frontend somewhere near https://github.com/datahq/frontend/blob/f3ff7c8b9f5e48b85af9a83043626e692969d945/lib/index.js#L33 you need to use that encoding and decode the descriptor

**Comment by zelima** [comment]
@Mikanebu can we guess encoding in frontend?

**Comment by Mikanebu** [comment]
@zelima let's give a try

**Comment by Mikanebu** [comment]
This should be fixed once frictionlessdata/datapackage-py#211 is merged and deployed.

**Comment by anuveyatsu** [comment]
@Mikanebu can you please test it now and close if fixed

**Comment by Mikanebu** [comment]
@anuveyatsu tested, it is not the correct title. I assigned `Réunion`, but on the showcase page, the title is `RÃ©union`. Please, see published dataset https://datahub.io/Mikanebu/hello-world

**Comment by Mikanebu** [comment]
FIXED, now we handle encoding descriptor as well. Published test dataset worked fine https://datahub.io/Mikanebu/hello-world-4
