### ISSUE TITLE
Embeddable HTML tables for resources

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#226]
As a Publisher, I want to be able to embed resources from my dataset as a HTML table in some post/website so:
- I can present my data from datahub for my audience.
- I can use processed data in my website.

## Acceptance criteria

* [x] I can do `https://datahub.io/core/finance-vix/r/0.html` and get a HTML table of the resource with index 0

## Tasks

* [x] Analysis
* [x] get the analysis reviewed and discussed
* [x] implementation

## Analysis

Refactor the existing route for `/:owner/:name/r/resourceNameOrIndex`:

0. identify the resource using given index/name
1. if resource is tabular (or geojson) + extension is `html`
    - yes: handle as embedable table or map (see below)
    - no: proceed as before

In case tabular + html ext:

1. prepare minified dp.json with the required resource
2. if tabular prepare a preview view
3. render using view.html template

Full vs preview resource:

Since we're using full resources when getting a resource by `/r/` link, we also could use entire resource for HTML tables. The drawback may be a that it may crash a browser if data is too large. So here some solutions:

- use preview resource (first 2k rows)
  - just like in the showcase page
- load first 5k rows (using frontend-showcase-js + tableshema set `{limit: 5000}` on read)
  - because we can afford more rows here as we load only the table
- get random sample of 1-2k rows (we already have this functionality)
  - but to do this we need to load entire file, which is not going to work

Ideally, we could improve our preview resources so instead of first 2k rows it would have the latest 2k rows for time series data. For non-time series data, we could keep showing first 2k rows.

**Decision:** frontend should not have too much of logic so we could do in the following order:
1. preview resource is available -> use it
2. no preview then use full resource

---

> How about checking the resource size? We have that info in dp.json. We could check if data is > XXX and if so do like github does. [name=irakli]

> Well, but we're already generating preview versions so why it cannot be done there? In the frontend we just use preview version if available, otherwise we use full one. [name=anu]

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/core/co2-ppm/r/2.html

**Comment by andylolz** [comment]
@anuveyatsu:

This is a COOL FEATURE!

I have a couple of requests!

1. I notice that consistent URLs also work i.e. for your example:
     * JSON: https://datahub.io/core/co2-ppm/r/co2-gr-mlo.json
     * CSV: https://datahub.io/core/co2-ppm/r/co2-gr-mlo.csv
     * HTML: https://datahub.io/core/co2-ppm/r/co2-gr-mlo.html ~~https://datahub.io/core/co2-ppm/r/2.html~~

    It would be cool to use these nicer URLs for the HTML version everywhere, rather than the numeric URLs
2. The cell highlighting is COOL! It would be great to be able to link to a highlighted version, [like linking to lines of code on github](https://github.com/datahq/frontend/blob/1ba6cdeb27beceb0d714be59062059e41e8a0a19/views/awesome.html#L18).

I’m not sure if I should open issues for these things on this repo, or elsewhere? Either way, THANKS for this cool feature!

**Comment by rufuspollock** [comment]
@andylolz thanks for the great feedback and **please** open issues for this kind of stuff on this repo -- this is exactly the place for it.

**Comment by anuveyatsu** [comment]
@andylolz I suppose @rufuspollock meant this repo - https://github.com/datahq/datahub-qa/issues - where you can open any kind of issues related to DataHub. You also can suggest new features or participate in existing one. This is also a good place to track activity and progress of the team. Additionally, here is the issues tracker dataset that helps you to have a sense of how much work is being done - https://datahub.io/examples/datahub-qa-issues-tracker

**Comment by andylolz** [comment]
Great! Thanks both!
