### ISSUE TITLE
User can’t see the failure reason of a dataset if it doesn’t have any successful revision.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#229]
Original source: https://github.com/datahq/datahub-qa/issues/140 from Adam

## Tasks

- [ ] rewrite the router logic so User could see the showcase page even if the dataset has an errors.

## Analysis

Error is here:
https://github.com/datahq/frontend/blob/378737c51937e86255d38f78bdbcbe34a4fe6fbf/routes/index.js#L389

**Comment by anuveyatsu** [comment]
@AcckiyGerman user always can see failed revisions but he/she must be the logged in as the owner. Was it discussed?

**Comment by AcckiyGerman** [comment]
@anuveyatsu Agree, probably @akariv forget to login, when got this bug.
