### ISSUE TITLE
Tidy up all html templates

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#28]
All HTML templates in `/views` are copied across from old `dpr-api` so there are lots of obsolete code, e.g., unnecessary/incorrect imports, old js scripts etc. We want to have neat HTML templates so page loading speed is as quick as possible.

## Acceptance criteria

* [ ] There are no extra line of code that is somehow irrelevant/unnecessary

## Tasks

* [ ] tidy up templates one by one (priorities are `base.html`, `home.html`, `showcase.html`)

**Comment by Mikanebu** [comment]
FIXED

**Comment by zelima** [comment]
@Mikanebu can you also tick the complete tasks/acceptance criteria
