### ISSUE TITLE
Take config settings from environment

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#30]
Have a bunch of hardcoded improtant config variables such as baseUrl (I think could probably have a better name e.g. SITE_URL - whilst api url could be API_URL).

https://github.com/datahq/frontend/blob/master/config/index.js

This is breaking login atm.

Recommend: stop using settings.json entirely and run off config vars in .env file (which we can auto use when running server locally see instructions in https://stackoverflow.com/questions/10560241/how-to-use-nodemon-with-env-files - we should add insructions like this to README.

## Tasks

* all key vars are from env variables
* vars are documented in README
* local running in dev mode using .env file and exporting to env before running is documented in developer / local running section of README

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/frontend/commit/aea23b5b5441b1b8553e57aa1dbe59bb44b6f8b0
