### ISSUE TITLE
Handle errors for packages in front page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#38]
We have 3 core packages and 3 tutorial packages on the front page and these packages are loaded from Rawstore. If one of the packages does not exist (or cannot be loaded from Rawstore), the front page does not load. We want to handle errors for these API calls and to not display packages if we could not get them.

Suggestions:
1. We can handle that error and remove section of the page with these packages
2. We can handle that error and display other packages instead
    * but what if entire rawstore is down? So probably not a good option

## Acceptance criteria

* [x] Front page loads even if rawstore is down

## Tasks

* [x] Handle error in `/lib/index.js` when getting a package (substitute with a stub package with title "Dataset not found!")

**Comment by rufuspollock** [comment]
Also what happens generally when we get a 404 from package store for a package at `/{owner}/{name}`? Do we 404 at the frontend gracefully?

**Comment by anuveyatsu** [comment]
FIXED - if we get error from rawstore, we handle it and load the front page. In the place of packages we will have error details, e.g., in the following screenshot top package is OK and bottom package was not found:

<img width="689" alt="screen shot 2017-07-19 at 12 50 28" src="https://user-images.githubusercontent.com/17809581/28354279-1d558446-6c81-11e7-8f42-8a25fe795c52.png">

**Comment by zelima** [comment]
@anuveyatsu Why not just ignore them? - if not found, not display. This looks strange to me

**Comment by anuveyatsu** [comment]
@zelima what if all 6 packages were not loaded? I think we should have some placeholders and showing error details can be helpful sometimes.

**Comment by zelima** [comment]
@anuveyatsu We are talking about the front page, right? Why would users want to see the error details of why some core packages are not displayed? They don't even expect them to be there right (at least when they arrive there for first time)?

**Comment by rufuspollock** [comment]
@anuveyatsu i actually inclined to agree with @zelima now i've seen the code. Let's just not add the package to the list of packages to show.

**Comment by anuveyatsu** [comment]
@rufuspollock @zelima just pushed a refactored code so now we just don't show packages that were not loaded from the rawstore.

**Comment by rufuspollock** [comment]
FIXED. However, there is a broader problem of handling 404s for packages and for package contents e.g. the README.
