### ISSUE TITLE
Error handler at topmost level

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#44]
No error should crash out the application entirely so we should have a top level error handler. This should:

* [x] report a reasonable error to the user (bonus for a cool 500 page ... - but that can be done later along with a cool 404 page)
* [x] log that error in detail internally

Here's the suggestion from https://expressjs.com/en/starter/faq.html

```
app.use(function (err, req, res, next) {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

**Comment by anuveyatsu** [comment]
FIXED. For now we show users simple message saying `Something failed. Please, try again later.` and log all detailed stack trace into `stderr`.
