### ISSUE TITLE
Show live status of publications

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#46]
* As a Publisher I can see status of publication immediately after I have pushed my package.

## Acceptance criteria

* [x] I can see status of my just published package online

## Tasks

* [x] Refactor according to algorithm in analysis below

### Algorithm for showing statuses

<img width="568" alt="screen shot 2017-08-09 at 21 57 02" src="https://user-images.githubusercontent.com/17809581/29131143-b87916e0-7d4d-11e7-8502-23db1950e3fb.png">

0. GET request to `/owner/name`
1. Check `pkgstore` for the package (in node)
    * found - render the showcase page [continue]
    * 404 - [continue]
2. Check `status` api in node (?)
    * LOADED, REGISTERED, RUNNING [continue]
      * if in showcase page - render mini `uploading` banner in the top
        * Go where notifications go
      * if `pkgstore` 404 - render `uploading.html` template
    * 404 [stop]
      * if in showcase page - do nothing
      * if `pkgstore` 404 - render 404
    * FAILED / SUCCEEDED
      * 
3. Check `status` api every 2s and with timeout of 20m
    * LOADED, REGISTERED, RUNNING
      * keep showing spinner + message saying it is processing
    * SUCCEEDED
      * success message 
          * if in showcase page: 
              * check if currently loaded datapackage hash == hash in stats
                  * if not equal, after 1-2s reload the page
                  * if equal, just hide `uploading` banner
          * if in `pkgstore` 404:
              * after 1-2s reload the page
    * FAILED
      * failure message and after 1-2s redirect to `./pipelines` (see below)

**Comment by anuveyatsu** [comment]
FIXED:

* if package's status is failed we print out all logs (should be improved in the future but now we only have logs)
* if package's status is `SUCCEEDED` we get the package from pkg-store and render the actual page
* if package's status one of `RUNNING`, `LOADED`, `REGISTERED`;
<img width="1280" alt="screen shot 2017-08-07 at 23 17 04" src="https://user-images.githubusercontent.com/17809581/29037886-5c6dee7a-7bc7-11e7-84cb-1a6af90ee05c.png">

**Comment by zelima** [comment]
@anuveyatsu I've  published something that errored  http://testing.datahub.io/zelima/nasa-tsv Seems it is not taking care of newlines making it impossible to read Trace

**Comment by akariv** [comment]
Please see new specstore API endpoints:
- `status` endpoint (https://github.com/datahq/specstore#status) should be used while waiting for result (i.e. in a not succeeded nor failed).
   - `logs` in the response can be used to show the user the running logs
- `info` endpoint should be used when we're in the final state (success or failure).
   - If the pipeline failed, `error_log` in the response is the exact error that caused the failure

**Comment by rufuspollock** [comment]
FIXED.
