### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#49]
have useful information on dashboard page - consult with Rufus.

* [ ] Email rather than username on dashboard page (and what about fullname?)
* [ ] 0 packages shown (inaccurately)

**Comment by rufuspollock** [comment]
Small tweaks are an hour but full design and thought is at least 8.

**Comment by anuveyatsu** [comment]
INVALID, this is already fixed in other issues. Visit your dashboard page (need to be logged in) to see the current state.
