### ISSUE TITLE
UTF-8 title rendering problem

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#58]
Title with UTF8 seems not rendered correctly - https://testing.datahub.io/adam.kariv/association-registry

**Comment by Mikanebu** [comment]
I have looked here https://pkgstore-testing.datahub.io/cd511289b5773fff5e7efe328846eef3/association-registry/latest/datapackage.json, and found that: "title": "×¢×××ª××ª ×¤×¢××××ª ××¨×©× ××¢×××ª××ª"

**Comment by rufuspollock** [comment]
INVALID. This is not an issue with the frontend but with the CLI - see https://github.com/datahq/datahub-cli/issues/154
