### ISSUE TITLE
Loading home page takes too long

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#61]
Currently, https://next.datahub.io/ is taking ~3s to load - we should get this under 1s. Right now, I think we should just hard code the info for the front page into the app (so no look ups etc ...).

## Acceptance criteria

* [ ] front page loads significantly quicker than the current one

## Tasks

* [ ]

**Comment by rufuspollock** [comment]
Whilst this can be annoying for local dev and we could improve performance, this is low on priority list for now IMO.

**Comment by anuveyatsu** [comment]
Closing for now as WONTFIX. We will reopen in the future if necessary.
