### ISSUE TITLE
datahub.io is not working over https

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#63]
https://datahub.io/ results with `502 Bad gateway`
actually, `521 web server is down` and 502 after

**Comment by zelima** [comment]
FIXED. was caused by misconfiguring the ssl certificates

**Comment by rufuspollock** [comment]
FIXED. This was my bad for leaving in an outdated page rule about ssl in cloudflare.

**Comment by justinclift** [comment]
Ahhh, yep, login is now working. :smile:
