### ISSUE TITLE
Misc theme items for 11 Sep 2017

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#74]
* [x] We are explicitly setting alerts in html (see home.html) - instead we should use the standard methods for setting announces in express (flash messages or similar)
* [x] Support setting class on body and setting in template so we can select specific pages to apply stuff too ... (e.g. home page should be home page only)
* [x] jumbotron => home(page).scss (jumbotron is the component) [30m]
* [x] footer styling (to be discussed) [30m]
* [x] redirect /x/y/z/ to /x/y/z (is this necessary?)       
* [x] do we still need jwt stuff in frontend-frontend js code e.g. in base.html `<script type="text/javascript" src="/static/vendor/jwt-decode.min.js"></script>` [20m]
* [x] Reinstate image logo in navabar - i think we want people to see DataHub there (at least until we get a "cooler" square) [15m]
* [x] Scripts in showcase page should come after the footer. Otherwise, it's causing delay when rendering the footer. [10m]
              

### Showing flash messages in Expressjs

After quick browsing found following 3 middlewares for ExpressJS:
* https://github.com/jaredhanson/connect-flash
* https://github.com/expressjs/express-messages
* https://github.com/expressjs/flash

As `connect-flash` has the most popularity, it was chosen for further analysis:

```javascript
// in index.js use the middleware somewhere after cookie parser:
const flash = require('connect-flash')
...
app.use(cookieParser())
app.use(flash())
...
```

> With the flash middleware in place, all requests will have a req.flash() function that can be used for flash messages.

Which means we can use flash messages in the following way:
```javascript
app.get('/logout', async (req, res) {
  req.flash('message', 'You have been successfully logged out.')
  res.redirect('/')
})

app.get('/', async (req, res) {
  res.render('home', { message: req.flash('message') })
})
```
and in `home.html`:
```html
<% if message %>
  <div class="alert alert-danger" role="alert">{{ message }}</div>
<% endif %>
```

##  Redirect /x/y/ to /x/y

```
app.use(function(req, res, next) {
  if(req.url.substr(-1) === '/' && req.url.length > 1) {
    res.redirect(301, req.url.slice(0, req.url.length-1));
  }
  else {
    next();
  }
});
```

**Comment by rufuspollock** [comment]
@anuveyatsu 

A. whilst the hanson may be popular i would not just go on popularity in selecting. Consider factors like last update (if that matters) e.g. it last had an update in 2013 (and has nine open pull requests which are old)! It is also not part of the expressjs org.

That said, looking at these three this looks like the one to go for 😄 (the others also are fairly old etc).

B. From your analysis and tasks it is not clear to me that you have thought about how you set this up and then render them for any page so i wanted to clarify that. You don't just want to render on home page - we might redirect to any page with flash messages. As such, you need to set these as template variables for all pages (express has a way to do that) and then add something in base.html (if possible).

**Comment by rufuspollock** [comment]
@anuveyatsu can you proceed to do the flash work and the redirect of /x/y/z/ - other items we need a short discussion.

**Comment by anuveyatsu** [comment]
@rufuspollock somehow missed your feedback to my analysis so implemented without considering it. The only thing is missing re your feedback is making flash messages available for all views. It can be fixed quickly:

1. setup middleware to store flash messages in `res.locals` so it is available from any view and only during the current request:

```javascript
// in index.js
app.use(function(req, res, next){
    res.locals.message = req.flash('message')
    next()
})
```

2. move html snippet from `home.html` to `base.html`:

```html
{% if message %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
{% endif %}
```

**Comment by anuveyatsu** [comment]
FIXED. See commits in this thread for more information.
