### ISSUE TITLE
Handle a lack of title in the data package

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#77]
If no title in DP we end up with an empty title on the showcase page.

Propose: If no title use the package name (perhaps suitable capitalized)

Example of no title: https://github.com/OriHoch/israel-crime-data/blob/master/data/traffic/datapackage.json

## Acceptance criteria

* [x] if a title is not provided, I can see a dataset's name as a title of showcase page.

## Tasks

* [x] refactor `showcase.html` template accroding to analysis

## Analysis

In here - https://github.com/datahq/frontend/blob/master/views/showcase.html#L27-L29 we need to have if statement that would render dataset name if a title is not provided:

```html
<h1>
  {% if dataset.title %}
    {{ dataset.title }}
  {% else %}
    {{ dataset.name }}
  {% endig %}
</h1>
```

**Comment by rufuspollock** [comment]
I'm holding off on this for now because i think this might be quite a minor situation and its unclear where this should be fixed ... - perhaps in the pipeline rather than front page. I'm therefore moving to icebox for now.

**Comment by rufuspollock** [comment]
@anuveyatsu i think we need to generate the title internally when we load a datapackage.json so we can use it everywhere e.g. we also need this on the listing pages (we get that info from ES i think ...)

**Comment by rufuspollock** [comment]
@anuveyatsu on second thoughts let's do the simplest thing possible and just use the name (with no special transformation) if no title in both showcase and listing (in keeping with minimizing logic in templates i guess we should do this in the controller before we pass down ...).

**Comment by anuveyatsu** [comment]
@rufuspollock we're already generating title when pushing single files using dataset's name and unslugifying + capitalizing it, e.g., `my-dataset` => `My dataset`.

On the other hand, we don't do anything for titles when user provides a `datapackage.json` so we probably want to use dataset's name when listing if no title provided.

**Comment by rufuspollock** [comment]
@anuveyatsu let's put this into current milestone as this should be a 1h fix for @Mikanebu to take on (it can be towards the end of the sprint).

The solution would be just using the name as is ...

**Comment by anuveyatsu** [comment]
FIXED

**Comment by rufuspollock** [comment]
@anuveyatsu when you close as FIXED please link to an example where you can see this working if you can 😄

**Comment by anuveyatsu** [comment]
To see the changes visit https://testing.datahub.io/anuar.ustayev, and below is how it looked like before this fix:

<img width="566" alt="screen shot 2017-11-28 at 17 14 38" src="https://user-images.githubusercontent.com/17809581/33316905-c754e22a-d45f-11e7-9c48-c27e30514a61.png">
