### ISSUE TITLE
README settings for large images

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#78]
Please, take a look at the following issue created by user: 
https://github.com/datahubio/qa/issues/2

## Acceptance criteria

* [x] images in README rendered correctly with appropriate width (e.g., https://datahub.io/OriHoch/israel-traffic-violations-2012-2016-partial-2017#readme )

## Tasks

* [x] refactor `sass` to set `max-width=100%` of all `img` tags in `/public/sass/_generals.scss`

**Comment by rufuspollock** [comment]
@anuveyatsu i would be a bit more selective and only set the max-width in the readme section of the showcase page. Was there a reason for doing this site wide?

**Comment by anuveyatsu** [comment]
@rufuspollock I don't think we need any `img` to have `width` of more than 100% of its wrapping tag. Note that setting `max-width` wouldn't break image's aspect ratio. But both cases would work.

**Comment by rufuspollock** [comment]
@anuveyatsu i'd still suggest just fixing for the readme for now ...

**Comment by anuveyatsu** [comment]
FIXED
