### ISSUE TITLE
Preview version of large datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#89]
We're adding preview version of large datasets into "extended" `datapackage.json`. E.g., for datasets with single CSV resource, there will be additional 3 versions of original resource - transformed CSV, JSON version + preview version. At the moment, in https://github.com/datahq/frontend/blob/master/lib/index.js#L170-L203, we're using derived CSV version for previews on showcase page. We want to make sure that `derived/preview` versions are also included in `alternates` property.

## Acceptance criteria

* [ ] Logical datapackage.json has the same length of resources as original one
* [ ] Alternates should contain all derived versions: CSV, JSON and preview

## Tasks

* [ ]

**Comment by justinclift** [comment]
Hmmm, what's your definition of "large" here? :smile:

**Comment by rufuspollock** [comment]
@justinclift large here means anything that loading into memory for a browser would be painful so i'd say anything over 5Mb CSV is pretty problematic and over ~20Mb tends to crash the browser. Our intention is to support any size of data file including GB+ size.

**Comment by justinclift** [comment]
Thanks, yep that makes sense. :smile:

**Comment by anuveyatsu** [comment]
INVALID. This was already working - https://github.com/datahq/frontend/blob/master/lib/index.js#L194
Main fixes re preview large datasets will happen in https://github.com/datahq/frontend-showcase-js/issues/168
