### ISSUE TITLE
Showcase page does not work when assembler is down

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#91]
Recently, assembler service was down and showcase page in the frontend was just hanging and timing out, which is not expected behaviour. In such case we want to render showcase page, if a dataset exists in the database or print some message saying users to try later.

## Acceptance criteria

* [x] when assembler is down (or too slow) we just render the page wihout status

## Tasks

* [x] refactor `routes/index.js` according to analysis

## Analysis

When pipelines status API is not responding (or responding too slow) we just render the showcase page without status. To reproduce such situation we can set time out for pipeline status API, e.g., for 10s and do page rendering after 5s without status.

1. make page rendering part of `:owner/:name` route a function so we can call it
2. have a function that triggers after 5s of timeout that calls page rendering function with empty state
3. set time out of 10s for pipeline status api response (temporary, should not be commited)
4. test out manually that page loads without status
5. if status api is OK it should clear timeout and render the page with status.

**Comment by rufuspollock** [comment]
@anuveyatsu i'd especially emphasize that the assembler is not, in theory, essential - for the frontend showcase. So if that timesout we continue in some sensible way (and we should be stricter on time outs - e..g only allow x seconds for a response). 

I think this issue needs more work to get it to a plan of work and then an estimate and then we can decide if worth prioritizing (assembler being down is rare so this may not be a priority).

**Comment by anuveyatsu** [comment]
@rufuspollock i need to complete at least 1st task in this issue to do more detailed analysis and figure out what exactly was the problem.

**Comment by anuveyatsu** [comment]
FIXED so now if pipelines api is down (or too slow) we load the showcase page without status.
