### ISSUE TITLE
[docs] add data info {dataset} to getting started

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#94]
* As Brook I want to run a simple non-side-effects command to see everything is working before I do something bigger so that I don’t damage anything and feel more certain …
    * I don’t want to write to my disk straight away … (where will it get written!)
    * data info https://datahub.io/core/finance-vix

## Acceptance criteria

* [x] when following getting started docs I have a simple non-side-effect command to check if the tool is working after installation

## Tasks

* [x] rewrite "Verifying" section in the http://datahub.io/docs/getting-started/installing-data so it suggests to do info command with some datahub dataset

**Comment by Mikanebu** [comment]
FIXED, added `data info` command with real example and output into getting started page

**Comment by anuveyatsu** [comment]
@Mikanebu please, create a new page "Getting started" where we should have things like `data info`. It can be quite small content. See more here - https://github.com/datahq/frontend/pull/95#issuecomment-330028276

**Comment by Mikanebu** [comment]
FIXED, there is a separate getting-started page for `data info` command
